# Generated by Django 5.1 on 2024-08-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('collageName', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=15)),
                ('currentSem', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('hscPercentage', models.IntegerField()),
                ('studentType', models.CharField(max_length=100)),
                ('baseName', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluko', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('hscResult', models.ImageField(upload_to='images/')),
                ('adharCard', models.ImageField(upload_to='images/')),
                ('collageFeeRecipt', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
