# Generated by Django 5.1 on 2024-08-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adharCard',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='collageFeeRecipt',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hscResult',
            field=models.FileField(upload_to='images/'),
        ),
    ]
