# Generated by Django 5.1 on 2024-08-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_student_hscpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hscPercentage',
            field=models.CharField(max_length=100),
        ),
    ]
