# Generated by Django 5.1 on 2024-08-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_alter_student_hscpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passportPhoto',
            field=models.FileField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
