# Generated by Django 5.1 on 2024-08-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_useradmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('passsWord', models.CharField(max_length=100)),
            ],
        ),
    ]
