# Generated by Django 5.1 on 2024-08-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_userstudent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstudent',
            name='status',
        ),
    ]
