# Generated by Django 5.1 on 2024-08-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_remove_userstudent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='status',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
