# Generated by Django 5.1 on 2024-08-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_userstudent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='Date',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='Time',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
