# Generated by Django 5.1 on 2024-08-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_userstudent_date_userstudent_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstudent',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='userstudent',
            name='Time',
        ),
    ]
