# Generated by Django 5.1 on 2024-08-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0015_userstudent_date_userstudent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='statusType',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
