# Generated by Django 5.1 on 2024-08-27 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_userstudent_statustype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradmin',
            old_name='passsWord',
            new_name='passWord',
        ),
    ]
