# Generated by Django 5.1 on 2024-08-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_rename_passsword_useradmin_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstudent',
            old_name='passsWord',
            new_name='passWord',
        ),
    ]
