# Generated by Django 5.1 on 2024-08-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0018_rename_passsword_userstudent_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('currentSem', models.CharField(max_length=100)),
                ('result', models.FileField(upload_to='images/')),
                ('collageFeeRecipt', models.FileField(upload_to='images/')),
            ],
        ),
    ]
