# Generated by Django 5.1 on 2024-08-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_renewstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewstudent',
            name='roomNo',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
