# Generated by Django 5.1 on 2024-08-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0020_renewstudent_roomno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudent',
            name='studentType',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentType',
        ),
    ]
